// Generates app/js/credit.js with an obfuscated, hash-locked "Designed by" credit.
// Usage: node scripts/set-credit.mjs "Designer Name"
// The name is stored as XOR-encoded bytes; at runtime the app decodes it and checks SHA-256 against the
// embedded digest. If either the bytes or the digest are edited, the check fails and the app refuses to start.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const name = process.argv[2];
if (!name || !name.trim()) { console.error('usage: node scripts/set-credit.mjs "Designer Name"'); process.exit(1); }
const clean = name.trim();
const key = crypto.randomBytes(16);
const bytes = Buffer.from(clean, 'utf8');
const enc = [...bytes].map((b, i) => b ^ key[i % key.length]);
const salt = crypto.randomBytes(8).toString('hex');
const digest = crypto.createHash('sha256').update(salt + clean).digest('hex');
// split the digest so the plain hex string does not appear in the file
const parts = [digest.slice(0, 20), digest.slice(20, 44), digest.slice(44)];

const out = `// Designed-by credit. Generated by scripts/set-credit.mjs — do not edit by hand.
// The credit text is XOR-encoded and verified against a SHA-256 digest at startup; the app will not run if it is altered.
const K = [${[...key].join(',')}];
const E = [${enc.join(',')}];
const S = '${salt}';
const D = ['${parts[0]}', '${parts[1]}', '${parts[2]}'];
let cached = null;
export function creditText() {
  if (cached) return cached;
  const b = new Uint8Array(E.length);
  for (let i = 0; i < E.length; i++) b[i] = E[i] ^ K[i % K.length];
  cached = new TextDecoder().decode(b);
  return cached;
}
export async function verifyCredit() {
  try {
    const data = new TextEncoder().encode(S + creditText());
    const buf = await crypto.subtle.digest('SHA-256', data);
    const hex = [...new Uint8Array(buf)].map((x) => x.toString(16).padStart(2, '0')).join('');
    return hex === D.join('');
  } catch { return false; }
}
export const CREDIT_LABEL = 'Designed by';
`;
const dest = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'app', 'js', 'credit.js');
fs.writeFileSync(dest, out);
console.log(`credit set to "${clean}" → ${dest}`);
