// Designed-by credit. Generated by scripts/set-credit.mjs — do not edit by hand.
// The credit text is XOR-encoded and verified against a SHA-256 digest at startup; the app will not run if it is altered.
const K = [224,86,125,88,165,127,211,37,172,110,166,119,118,60,218,69];
const E = [161,55,21,57,215,95,135,64,205,3];
const S = '95f7c43ab699f758';
const D = ['d9710dbe8a9a3e897f55', '58cfe4b74a6bb0dd115d1361', 'cadb14f7205909d7833a'];
let cached = null;
export function creditText() {
  if (cached) return cached;
  const b = new Uint8Array(E.length);
  for (let i = 0; i < E.length; i++) b[i] = E[i] ^ K[i % K.length];
  cached = new TextDecoder().decode(b);
  return cached;
}
export async function verifyCredit() {
  try {
    const data = new TextEncoder().encode(S + creditText());
    const buf = await crypto.subtle.digest('SHA-256', data);
    const hex = [...new Uint8Array(buf)].map((x) => x.toString(16).padStart(2, '0')).join('');
    return hex === D.join('');
  } catch { return false; }
}
export const CREDIT_LABEL = 'Designed by';
