// Designed-by credit. Generated by scripts/set-credit.mjs — do not edit by hand.
// The credit text is XOR-encoded and verified against a SHA-256 digest at startup; the app will not run if it is altered.
const K = [120,29,12,134,78,148,75,247,254,96,4,253,82,38,84,188];
const E = [55,121,99,245];
const S = 'e6f7c67a9320b9e9';
const D = ['ed4115a9e954ec9f21e0', '29a223d795679c4cf7d0915a', '8e857858d9c6591c41c3'];
let cached = null;
export function creditText() {
  if (cached) return cached;
  const b = new Uint8Array(E.length);
  for (let i = 0; i < E.length; i++) b[i] = E[i] ^ K[i % K.length];
  cached = new TextDecoder().decode(b);
  return cached;
}
export async function verifyCredit() {
  try {
    const data = new TextEncoder().encode(S + creditText());
    const buf = await crypto.subtle.digest('SHA-256', data);
    const hex = [...new Uint8Array(buf)].map((x) => x.toString(16).padStart(2, '0')).join('');
    return hex === D.join('');
  } catch { return false; }
}
export const CREDIT_LABEL = 'Designed by';
